name:                alignment
version:             0.1.0.0
github:              "jonathanjameswatson/alignment"
license:             BSD3
author:              "Jonathan Watson"
maintainer:          "23344719+jonathanjameswatson@users.noreply.github.com"
copyright:           "2022 Jonathan Watson"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jonathanjameswatson/alignment#readme>

dependencies:
- base >= 4.7 && < 5
- lens >= 5
- mtl
- vector >= 0.12
- optparse-applicative >= 0.16

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  alignment-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - alignment

tests:
  alignment-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - alignment
    - tasty
    - tasty-golden
    - filepath
    - utf8-string
