name: CI
on: push
jobs:
  ormolu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mrkkrp/ormolu-action@v7
  build:
    runs-on: ubuntu-latest
    needs: ormolu
    strategy:
      matrix:
        ghc: ["8.10.7", "9.0.2"]
      fail-fast: true
    name: GHC ${{ matrix.ghc }}
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          enable-stack: true
      - name: Install dependencies
        run: stack build --fast --skip-ghc-check --no-terminal --test --only-dependencies
      - name: Build
        run: stack build --fast
      - name: Test
        run: stack test --fast
